### ISSUE TITLE
bug: Clicking delete icon crashed while right after triggering update Data

### ISSUE THREAD

**Issue by biaomingzhong** [thanhviet-ucan/SmartListAdapter#3]
Logcat: 

```
java.lang.ArrayIndexOutOfBoundsException: length=6; index=-1
  at java.util.ArrayList.remove(ArrayList.java:480)
  at com.thanhviet.smartlistadapter.MainActivity.deleteNote(MainActivity.kt:19)
  at com.thanhviet.smartlistadapter.MainActivity.access$deleteNote(MainActivity.kt:10)
```

**Comment by biaomingzhong** [comment]
I think it is because you replace data with a new list before removing last list larger index item

**Comment by abuenovanadis** [comment]
Hello, and how can control this? I write try catch to avoid crash...

**Comment by thanhviet-ucan** [comment]
@biaomingzhong : You are right!!! Can you fighting it ? :) You can create a pull request to resolved this issue, I think it's useful for an other.

**Comment by biaomingzhong** [comment]
@thanhviet-ucan I think that you shouldn't use any `adapter.notify...` API anymore. You should just call submitList instead calling `adapter.notify...` API Because you are using ListAdapter with DiffUtil which internal diff calculate list change to optimize `adapter.notify...` API's usage
